name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: "AIzaSyCWbewCRdLhjHD73Y5Jt5hoUmbJFDQmkyc"
          VITE_FIREBASE_AUTH_DOMAIN: "task-tracker-app-65dab.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "task-tracker-app-65dab"
          VITE_FIREBASE_STORAGE_BUCKET: "task-tracker-app-65dab.firebasestorage.app"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "744363781870"
          VITE_FIREBASE_APP_ID: "1:744363781870:web:aeb212bc0f13f64b14cdff"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
